### ISSUE TITLE
How to set username and password?

### ISSUE THREAD

**Issue by mjschmidt** [dirigiblelabs/charts#1]
I was able to deploy but cannot login, what is the default username and password and how do I override these values?

**Comment by ThuF** [comment]
Hi @mjschmidt the default values login are `dirigible` \ `dirigible` 
- https://www.dirigible.io/help/setup_tomcat.html
- https://www.dirigible.io/help/setup.html

For production use case we recommend to use external IDP as Keycloak for example: https://www.dirigible.io/blogs/2018/06/25/kubernetes_keycloak_postgresql_dirigible.html

For the `SAP` release, they are configured to use the default IDP of the SAP Cloud Platform: https://download.eclipse.org/dirigible/drops/R-4.6-202005311900/index.html

**Comment by mjschmidt** [comment]
Thanks, I am just getting started with it and checking it out but yeah for prod can you hook this to any oauth/openidconnect/saml provider?

**Comment by ThuF** [comment]
@mjschmidt we can enhance the chart to support automated deployment together with Keycloak, or at least to be able to change the default login values.

If that matches your request, would you be so kind to write an issue in our main GitHub repository: https://github.com/eclipse/dirigible

You can also try dirigible from our main site: https://www.dirigible.io/ -> `Try It Out` button

**Comment by ThuF** [comment]
@mjschmidt here are some getting started materials:
- https://www.youtube.com/c/dirigibleio
- https://www.dirigible.io/samples/
- https://www.dirigible.io/api/
- https://www.dirigible.io/help/

**Comment by mjschmidt** [comment]
Yeah I think just being able to change the login values to start would be good. My use case is for an offline environment currently. And we have oauth, openid connect, and saml security integration options. Keycloak is not espeicially easy to maintain yourself or I would totally hook that up to my openid connect provider then hook this to that. I was just wondering if this happened to have a more generic security integration point.

**Comment by mjschmidt** [comment]
Since I am right now just looking to setu a web based programing server for my team, i don't necessarily need all the security right now either :)

**Comment by mjschmidt** [comment]
knowing the default user name and pass works for me at the moment!

It worked!

**Comment by ThuF** [comment]
Great, then I'll close this issue for now.

@mjschmidt  if you have any question, request or if you want to have some in-depth session about Eclipse Dirigible, you can contact us on: dirigible-dev@eclipse.org, https://eclipse-dirigible.slack.com or just write an issue on https://github.com/eclipse/dirigible

Regards,
Yordan

**Comment by mjschmidt** [comment]
due to the license I can't contribute to it, my company only lets me contribute to apache

but looking at the chart it looks like you would just have to make some minor changes to the env section of the deployment yaml and the values file.

**Comment by mjschmidt** [comment]
and thanks!
